const getUserAssetsMock = [
  {
    code: "TD",
    name: "Tesouro Selic 2026 (LFT)",
    type: "Tesouro",
    value: 10.24,
    quantity: 15,
  },
  {
    code: "TI",
    name: "Tesouro IPCA 2029",
    type: "Tesouro",
    value: 80,
    quantity: 40,
  },
  {
    code: "AC",
    name: "Agro3 - BRASILAGRO",
    type: "Ação",
    value: 13.77,
    quantity: 17,
  },
  {
    code: "FII",
    name: "VISC11 - FII VINCI SC",
    type: "Fundo",
    value: 26.3,
    quantity: 13,
  },
  {
    code: "BBAS3",
    name: "Banco do Brasil S.A.",
    type: "Ação",
    value: 42.15,
    quantity: 3,
  },
  {
    code: "BBDC4",
    name: "Bradesco PN",
    type: "Ação",
    value: 13.4,
    quantity: 12,
  },
  {
    code: "SANB11",
    name: "Santander BR Units",
    type: "Ação",
    value: 32.5,
    quantity: 22,
  },
  {
    code: "MXRF11",
    name: "FII Maxi Renda",
    type: "Fundo",
    value: 10.02,
    quantity: 5,
  },
  {
    code: "RURA11",
    name: "FII Rura Agro",
    type: "Fundo",
    value: 104.5,
    quantity: 35,
  },
  {
    code: "KNCR11",
    name: "FII Kinea Rendimentos",
    type: "Fundo",
    value: 96.3,
    quantity: 9,
  },
  {
    code: "ETH",
    name: "Ethereum",
    type: "Cripto",
    value: 1600.45,
    quantity: 1,
  },
];

export default getUserAssetsMock;
